[package]
name = "luminy_core"
version = "0.1.0"
edition = "2021"

[dependencies]
configparser = "1.0"
blake3 = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
base58 = "0.1"
ecdsa = "0.16"
k256 = "0.12"
base64ct = "1.7.1"